name: Multi-Scrobbler
version: 0.10.0
slug: multi-scrobbler
description: Scrobble plays from multiple sources to multiple clients. Supports Spotify, Jellyfin, Plex, Last.fm, ListenBrainz, and more.
url: https://github.com/FoxxMD/multi-scrobbler
codenotary: bigsby@bytemail.uk
webui: http://[HOST]:[PORT:9078]
init: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  9078/tcp: 9078
ports_description:
  9078/tcp: Web interface
image: docker.io/foxxmd/multi-scrobbler:latest